{$IFDEF FPC}
{$MODE Delphi}
{$CODEPAGE cp1251}
{$GOTO OFF}
{$ENDIF}
{$IFNDEF FPC}
{$DEFINE DELPHI}
{$ENDIF}
{$IFDEF DELPHI32}
{$DEFINE DELPHI}
{$ENDIF}
{$IFDEF DELPHI64}
{$DEFINE DELPHI}
{$ENDIF}
{$IFDEF DELPHI}
{$IFDEF CPUX86}
{$DEFINE CPU32}
{$ENDIF}
{$IFDEF CPUX64}
{$DEFINE CPU64}
{$ENDIF}
{$ENDIF}
{$IFNDEF FPC}
{$IFDEF CPU64}
{$DEFINE CPUX64}
{$ENDIF}
{$IFDEF CPU32}
{$DEFINE CPUX86}
{$ENDIF}
{$ENDIF}
{$DEFINE StreamType}
{$DEFINE REDGREEN}
{$IFNDEF FPC}
{$DEFINE DELPHI}
{$ENDIF}
// {$DEFINE BLACKWHITE}

// {$DEFINE DCLDEBUG}
// {$DEFINE EMBEDDED}


{$IFNDEF FPC}
// {$DEFINE ADO}
// {$DEFINE ZEOS}
// {$DEFINE BDE}
  {$DEFINE IB}
{$ENDIF}
{$IFDEF FPC}
  {$DEFINE ZEOS}
//  {$DEFINE ZVComponents}
{$ENDIF}

{$IFDEF VER260}
{$DEFINE NONEOLDCOMPONENTS}
{$DEFINE NEWDELPHI}
{$ENDIF}
{$IFDEF ADO}
{$DEFINE PARAMS2}
{$ENDIF}
{$IFDEF BDE}
{$DEFINE BDE_or_IB}
{$DEFINE CACHEON}
{$ENDIF}
{$IFDEF IB}
{$DEFINE BDE_or_IB}
{$DEFINE IBALL}
{$DEFINE CACHEON}
{$ENDIF}
{$IFDEF ZEOS}
{$DEFINE PARAMS2}
{$DEFINE BDE_or_IB}
{$DEFINE CACHEON}
{$DEFINE IBALL}
{$ENDIF}
{$IFDEF EMBEDDED}
{$DEFINE NODCLMESSAGES}
{$ENDIF}
