/******************************************************************************/
/***          Generated by IBExpert 2007.05.23 18.07.2007 11:14:46          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'LOCALHOST:C:\DB\Template.FDB'
USER 'SYSDBA' PASSWORD 'tango'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_SEQNUM_REF_ID;
CREATE GENERATOR GEN_SCRIPTS_ID;

SET TERM ^ ; 

/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/

CREATE PROCEDURE ADD_MENU_ITEM_TO_ROLE (
    ROLEID INTEGER,
    MENUITEMID INTEGER)
RETURNS (
    ISAPPEND INTEGER)
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE COPY_ROLE (
    ROLEIDFROM INTEGER,
    ROLEIDTO INTEGER)
AS
BEGIN
  EXIT;
END^


CREATE PROCEDURE DAY_NUMB (
    ADATE DATE)
RETURNS (
    RESULT INTEGER)
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE DAY_OF_WEEK (
    ADATE DATE)
RETURNS (
    RESULT INTEGER)
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE DAYS_OF_YEAR (
    ADATE DATE)
RETURNS (
    RESULT INTEGER)
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE DEL_ROLE_AND_MENU (
    ROLEID INTEGER)
AS
BEGIN
  EXIT;
END^


CREATE PROCEDURE DEL_ROLE_MENU (
    ROLEID INTEGER)
AS
BEGIN
  EXIT;
END^


CREATE PROCEDURE DISTANCE_OF_DATES (
    ADATE_BEG DATE,
    ADATE_END DATE)
RETURNS (
    RESULT INTEGER)
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE EXIT_USERS (
    USER_NAME VARCHAR(50) CHARACTER SET WIN1251)
AS
BEGIN
  EXIT;
END^


CREATE PROCEDURE EXTRACT_MONTH (
    ADATE DATE)
RETURNS (
    MONTH_NUM INTEGER)
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE EXTRACT_YEAR (
    ADATE DATE)
RETURNS (
    YEAR_NUM INTEGER)
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE FIRST_DAY_OF_MONTH (
    ADATE DATE)
RETURNS (
    RESULT DATE)
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE FIRST_DAY_OF_NEXT_MONTH (
    ADATE DATE)
RETURNS (
    RESULT DATE)
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE LAST_DAY_OF_MONTH (
    ADATE DATE)
RETURNS (
    RESULT DATE)
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE MONTH_LENGTH (
    ADATE DATE)
RETURNS (
    RESULT INTEGER)
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE MONTH_NUM (
    ADATE DATE)
RETURNS (
    MONTH_NUM INTEGER)
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE WEEK_NUMBER (
    ADATE DATE)
RETURNS (
    RESULT INTEGER)
AS
BEGIN
  SUSPEND;
END^



SET TERM ; ^


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE ACTIVE_USERS (
    UID          INTEGER,
    USER_NAME    VARCHAR(25) CHARACTER SET NONE,
    ATIME        TIMESTAMP,
    ACTION_TYPE  VARCHAR(25) CHARACTER SET NONE
);

CREATE TABLE GLOBAL_PARAMS (
    PARAM_ID      INTEGER,
    PARAMCAPTION  VARCHAR(30) CHARACTER SET NONE,
    PARAMNAME     VARCHAR(15) CHARACTER SET NONE,
    PARAMVALUE    VARCHAR(54) CHARACTER SET NONE
);

CREATE TABLE ROLES (
    ROLEID        INTEGER NOT NULL,
    ROLENAME      CHAR(20) CHARACTER SET NONE,
    LONGROLENAME  CHAR(15) CHARACTER SET NONE,
    ROLEPASS      CHAR(25) CHARACTER SET NONE
);

CREATE TABLE ROLESMENU (
    ROLEID      INTEGER NOT NULL,
    MENUITEMID  INTEGER
);

CREATE TABLE SCRIPTS (
    NUMSEQ   INTEGER NOT NULL,
    DCLNAME CHAR(50),
    DCLTEXT BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    COMMAND CHAR(80),
    IDENT INTEGER,
    PARENT INTEGER);

/******************************************************************************/
/***                                 Views                                  ***/
/******************************************************************************/


/* View: ROLESTOMENU */
CREATE VIEW ROLESTOMENU(
    ROLEID,
    ROLENAME,
    LONGROLENAME,
    MENUITEMID,
    DCLNAME)
AS
select r.roleid roleid, r.rolename, r.longrolename, rm.MENUITEMID, d.dclname from RolesMenu rm, Roles r, SCRIPTS d
where r.roleid=rm.roleid and rm.MENUITEMID=d.numseq
;


INSERT INTO ROLES (ROLEID, ROLENAME, LONGROLENAME, ROLEPASS) VALUES (33, '111', '11-00', '1');

COMMIT WORK;



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE ROLES ADD CONSTRAINT PK_ROLES PRIMARY KEY (ROLEID);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX ROLESMENU_IDX1 ON ROLESMENU (ROLEID, MENUITEMID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;


/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: ACTIVE_USERS_BI */
CREATE TRIGGER ACTIVE_USERS_BI FOR ACTIVE_USERS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.uid is null) then
    new.uid = gen_id(gen_seqnum_ref_id,1);
  new.atime='now';
end
^

/* Trigger: GLOBAL_PARAMS_BI */
CREATE TRIGGER GLOBAL_PARAMS_BI FOR GLOBAL_PARAMS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.PARAM_ID IS NULL) THEN
    NEW.PARAM_ID = GEN_ID(gen_seqnum_ref_id,1);
END
^

/* Trigger: ROLES_BI */
CREATE TRIGGER ROLES_BI FOR ROLES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ROLEID IS NULL) THEN
    NEW.ROLEID = GEN_ID(GEN_SEQNUM_REF_ID,1);
END
^

SET TERM ; ^



/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/


SET TERM ^ ;

ALTER PROCEDURE ADD_MENU_ITEM_TO_ROLE (
    ROLEID INTEGER,
    MENUITEMID INTEGER)
RETURNS (
    ISAPPEND INTEGER)
AS
declare variable tmp1 integer;
begin
select Count(r.roleid) from rolesmenu r where r.roleid=:roleid and r.menuitemid=:menuitemid into tmp1;
if (:tmp1=0) then
begin
    Insert into rolesmenu(roleid, menuitemid) values(:roleid, :menuitemid);
    ISAPPEND=1;
    suspend;
end
else
begin
ISAPPEND=0;
suspend;
end
end
^

ALTER PROCEDURE COPY_ROLE (
    ROLEIDFROM INTEGER,
    ROLEIDTO INTEGER)
AS
begin
insert into rolesmenu select :roleidto, MENUITEMID from rolesmenu r where r.roleid=:roleidfrom;
end
^

ALTER PROCEDURE DAY_NUMB (
    ADATE DATE)
RETURNS (
    RESULT INTEGER)
AS
begin
Result=EXTRACT(YEARDAY FROM ADate)+1;
  suspend;
end
^

ALTER PROCEDURE DAY_OF_WEEK (
    ADATE DATE)
RETURNS (
    RESULT INTEGER)
AS
declare variable elapsed integer;
BEGIN
  Elapsed=ADate-Cast('1.1.1996' as Date);
  if (Elapsed = 0) THEN
  Result = 0;
  ELSE
  Result = Elapsed-(CAST((Elapsed / 7)-0.5 AS INTEGER)*7);
suspend;
END
^

ALTER PROCEDURE DAYS_OF_YEAR (
    ADATE DATE)
RETURNS (
    RESULT INTEGER)
AS
BEGIN
  IF ( 2 = EXTRACT(MONTH FROM (ADate - EXTRACT(YEARDAY FROM ADate) + 59)) ) THEN
    Result = 366;
  ELSE
    Result = 365;
suspend;
END
^

ALTER PROCEDURE DEL_ROLE_AND_MENU (
    ROLEID INTEGER)
AS
begin
delete from rolesmenu r where r.roleid=:roleid;
Delete from roles r where r.roleid=:roleid;
end
^

ALTER PROCEDURE DEL_ROLE_MENU (
    ROLEID INTEGER)
AS
begin
delete from rolesmenu r where r.roleid=:roleid;
end
^

ALTER PROCEDURE DISTANCE_OF_DATES (
    ADATE_BEG DATE,
    ADATE_END DATE)
RETURNS (
    RESULT INTEGER)
AS
begin
Result=ADATE_END-ADATE_BEG;
  suspend;
end
^

ALTER PROCEDURE EXIT_USERS (
    USER_NAME VARCHAR(50) CHARACTER SET WIN1251)
AS
declare variable tmp1 integer;
begin
select max(au.uid) from ACTIVE_USERS au where au.USER_NAME=:user_name into :tmp1;
delete from ACTIVE_USERS au where au.USER_NAME=:user_name and au.uid=:tmp1;
delete from ACTIVE_USERS t where CAST(substring(Cast(t.atime as timestamp) from 1 for 10) as DATE)<CAST(substring(Cast('now' as timestamp) from 1 for 10) as DATE);
end
^

ALTER PROCEDURE EXTRACT_MONTH (
    ADATE DATE)
RETURNS (
    MONTH_NUM INTEGER)
AS
begin
if (:adate is null) then adate='now';
month_num=extract(month from ADate);
  suspend;
end
^

ALTER PROCEDURE EXTRACT_YEAR (
    ADATE DATE)
RETURNS (
    YEAR_NUM INTEGER)
AS
begin
if (:adate is null) then adate='now';
year_num=extract(year from ADate);
  suspend;
end
^

ALTER PROCEDURE FIRST_DAY_OF_MONTH (
    ADATE DATE)
RETURNS (
    RESULT DATE)
AS
begin
Result=ADate-EXTRACT(DAY FROM ADate) + 1;
  suspend;
end
^

ALTER PROCEDURE FIRST_DAY_OF_NEXT_MONTH (
    ADATE DATE)
RETURNS (
    RESULT DATE)
AS
begin
Result=ADate-EXTRACT(DAY FROM ADate) + 32;
Result=Result-EXTRACT(DAY FROM Result) + 1;
  suspend;
end
^

ALTER PROCEDURE LAST_DAY_OF_MONTH (
    ADATE DATE)
RETURNS (
    RESULT DATE)
AS
begin
Result=ADate-EXTRACT(DAY FROM ADate) + 32;
Result=Result-EXTRACT(DAY FROM Result);
  suspend;
end
^

ALTER PROCEDURE MONTH_LENGTH (
    ADATE DATE)
RETURNS (
    RESULT INTEGER)
AS
declare variable tmp date;
BEGIN
    TMP = ADate - EXTRACT(DAY FROM ADate) + 32;
    Result  = EXTRACT(DAY FROM (TMP - EXTRACT(DAY FROM TMP)));
suspend;
END
^

ALTER PROCEDURE MONTH_NUM (
    ADATE DATE)
RETURNS (
    MONTH_NUM INTEGER)
AS
begin
if (:adate is null) then adate='now';
month_num=extract(month from ADate);
  suspend;
end
^

ALTER PROCEDURE WEEK_NUMBER (
    ADATE DATE)
RETURNS (
    RESULT INTEGER)
AS
declare variable w integer; /* week number */
declare variable y integer; /* year the week belongs to */
BEGIN
  Result = ((EXTRACT(YEARDAY FROM ADate) - EXTRACT(WEEKDAY FROM ADate-1) + 7) / 7e0)+1;
  SUSPEND;
END
^


SET TERM ; ^

SET BLOBFILE 'Scripts.lob';

/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE SCRIPTS ADD CONSTRAINT PK_SCRIPTS PRIMARY KEY (NUMSEQ);

/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX SCRIPTS_IDX1 ON SCRIPTS (IDENT, PARENT, DCLNAME);

/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/

SET TERM ^ ;

/* Trigger: SCRYPTS_SETNUM */
CREATE TRIGGER SCRYPTS_SETNUM FOR SCRIPTS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
IF (NEW.NumSeq IS NULL) THEN
    NEW.NumSeq = GEN_ID(GEN_SCRIPTS_ID,1);
end
^

SET TERM ; ^

INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('Настройки', NULL, '', 900, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('', NULL, NULL, 20001, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('Заголовок приложения', NULL, NULL, 0, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('Права доступа', NULL, '', 800, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('Версия...', :h00000000_00000008, '', 9001, 900);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('Роли', NULL, 'Roles', 2005, 800);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('Меню ролей', NULL, 'RolesMenu', 2006, 800);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('AddMenuItemScr', :h00000008_0000001B, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('AddMenuItem', :h00000023_000001D9, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('AddRoleExec', :h000001FC_0000010C, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('CopyRoleExec', :h00000308_0000006A, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('CopyRole', :h00000372_000001BD, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('Roles', :h0000052F_000000BA, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('CopyRole_Call', :h000005E9_00000018, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('DelRole', :h00000601_00000045, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('DelRoleExec', :h00000646_00000058, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('DelRoleMenuItem', :h0000069E_000000E2, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('InitApp', :h00000780_0000003B, '', 40001, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('GlobalParams', :h000007BB_000001A0, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('RunAddGlbParam', :h0000095B_0000001E, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('AddGlbParamDlg', :h00000979_00000180, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('RunEditGlbParam', :h00000AF9_0000001B, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('EditGlbParam', :h00000B14_000000A8, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('Параметры', NULL, 'GlobalParams', 2010, 900);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('RolesMenu', :h00000BBC_000002E0, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('DelRolesMenuItem', :h00000E9C_0000011B, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('Справочники', NULL, '', 1, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('DelRolesMenuItem_Call', :h00000FB7_00000020, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES (NULL, :h00000FD7_0000004F, NULL, 20002, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('SQL Monitor', :h00001026_00000007, '', 9000, 900);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('InitScrypt40002', :h0000102D_0000006E, NULL, 40002, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('TerminateScrypt40101', :h0000109B_0000004D, NULL, 40101, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('ActiveUsers', :h000010E8_00000181, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('Активные пользователи', NULL, 'ActiveUsers', 9005, 800);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('del_currr_user', :h00001269_0000004F, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('clear_all_users', :h000012B8_0000002C, NULL, NULL, NULL);
INSERT INTO SCRIPTS (DCLNAME, DCLTEXT, COMMAND, IDENT, PARENT) VALUES ('ExecAddGlbParam', :h000012E4_000000A5, NULL, NULL, NULL);

COMMIT WORK;
