DROP TRIGGER ROLESMENU_BI;
DROP TABLE ROLESMENU;
DROP TRIGGER ROLES2_BI;
DROP TABLE ROLES2;
DROP TRIGGER ROLES_BI;
DROP TABLE ROLES;
DROP TABLE ROLES2MENU2;
DROP TRIGGER SCRIPTS2_BI;
DROP TABLE SCRIPTS2;
DROP TRIGGER NOTIFYCATIONS_BI0;
DROP TABLE NOTIFYCATIONS;
DROP TRIGGER GLOBAL_PARAMS_BI;
DROP TABLE GLOBAL_PARAMS;
DROP TRIGGER TEMPL_BI;
DROP TABLE TEMPL;

--------------------------
DROP TRIGGER SCRIPTS_BI;
DROP TABLE SCRIPTS;
--------------------------

COMMIT;