CREATE DOMAIN DM_PASSWORD AS
VARCHAR(35);

update RDB$RELATION_FIELDS set
RDB$FIELD_SOURCE = 'DM_PASSWORD'
where (RDB$FIELD_NAME = 'DCL_USER_PASS') and (RDB$RELATION_NAME = 'DCL_USERS');

COMMIT;

ALTER TABLE DCL_INI_PROFILES
ADD TEMP_BLOB BLOB SUB_TYPE 1 SEGMENT SIZE 4096 CHARACTER SET WIN1251 ;

UPDATE DCL_INI_PROFILES I
SET I.TEMP_BLOB = I.INI_PARAM_VALUE;

ALTER TABLE DCL_INI_PROFILES DROP INI_PARAM_VALUE;

ALTER TABLE DCL_INI_PROFILES
ADD INI_PARAM_VALUE BLOB SUB_TYPE 1 SEGMENT SIZE 2048 CHARACTER SET WIN1251 ;

COMMIT;

UPDATE DCL_INI_PROFILES I
SET I.INI_PARAM_VALUE = I.TEMP_BLOB;

ALTER TABLE DCL_INI_PROFILES DROP TEMP_BLOB;

COMMIT;

ALTER TABLE DCL_INI_PROFILES
ADD INI_TYPE INTEGER;

COMMIT;

ALTER TABLE DCL_NOTIFYCATIONS DROP CONSTRAINT FK_DCL_NOTIFYCATIONS_1;

ALTER TABLE DCL_NOTIFYCATIONS
ADD CONSTRAINT FK_DCL_NOTIFYCATIONS_1
FOREIGN KEY (USER_ID)
REFERENCES DCL_USERS(UID)
ON DELETE CASCADE
ON UPDATE CASCADE
USING INDEX FK_DCL_NOTIFYCATIONS_1;

COMMIT;

UPDATE DCL_INI_PROFILES SET INI_TYPE=1;

COMMIT;


ALTER TABLE DCL_TEMPLATES
ADD TEMPL_DATATYPE INTEGER;

COMMIT;