DROP TRIGGER DCL_ROLES_BI;
DROP TRIGGER DCL_ROLESMENU_BI;
DROP TRIGGER DCL_USERS_BI;
DROP TRIGGER DCL_ROLES_TO_USERS_BI;
DROP TRIGGER DCL_ACTIVE_USERS_BI;
DROP TRIGGER DCL_NOTIFYCATIONS_BI0;
DROP TRIGGER DCL_USER_LOGIN_HISTORY_BI;
DROP TRIGGER DCL_GLOBAL_PARAMS_BI;
DROP TRIGGER DCL_TEMPLATES_BI;
DROP TRIGGER DCL_SCRIPTS_BI;
DROP TRIGGER INI_PROFILES_BI;
DROP TRIGGER ORGANIZATIONS_BI;

ALTER TABLE DCL_USER_LOGIN_HISTORY DROP CONSTRAINT FK_DCL_USER_LOGIN_HISTORY_1;
ALTER TABLE DCL_ACTIVE_USERS DROP CONSTRAINT FK_DCL_ACTIVE_USERS_1;
ALTER TABLE DCL_INI_PROFILES DROP CONSTRAINT FK_DCL_INI_PROFILES_1;
ALTER TABLE DCL_NOTIFYCATIONS DROP CONSTRAINT FK_DCL_NOTIFYCATIONS_1;
ALTER TABLE DCL_ROLESMENU DROP CONSTRAINT FK_DCL_ROLESMENU_1;
ALTER TABLE DCL_ROLESMENU DROP CONSTRAINT FK_DCL_ROLESMENU_2;
ALTER TABLE DCL_ROLES_TO_USERS DROP CONSTRAINT FK_DCL_ROLES_TO_USERS_1;
ALTER TABLE DCL_ROLES_TO_USERS DROP CONSTRAINT FK_DCL_ROLES_TO_USERS_2;
ALTER TABLE DCL_USERS DROP CONSTRAINT FK_DCL_USERS_1;
---ALTER TABLE DCL_USERS DROP CONSTRAINT PK_DCL_USERS;

DROP PROCEDURE ADD_MENU_ITEM_TO_ROLE;
DROP PROCEDURE COPY_ROLE;
DROP PROCEDURE DEL_ROLE_AND_MENU;
DROP PROCEDURE DEL_ROLE_MENU;
DROP PROCEDURE ROLESMENU_IS_CORRECT;

DROP VIEW ROLESTOMENU;

DROP TABLE DCL_ROLES;
DROP TABLE DCL_USERS;
DROP TABLE DCL_USER_LOGIN_HISTORY;
DROP TABLE DCL_ACTIVE_USERS;
DROP TABLE DCL_INI_PROFILES;
DROP TABLE DCL_NOTIFYCATIONS;
DROP TABLE DCL_TEMPLATES;
DROP TABLE DCL_GLOBAL_PARAMS;
DROP TABLE DCL_ROLES_TO_USERS;
DROP TABLE DCL_ROLESMENU;
DROP TABLE DCL_SCRIPTS;

DROP SEQUENCE GEN_DCL_ACTIVE_USERS_ID;
DROP SEQUENCE GEN_DCL_USER_LOGIN_HISTORY_ID;
DROP SEQUENCE GEN_INI_PROFILES_ID;
--DROP SEQUENCE DCL_MAIN_GENERATOR_ID;
DROP SEQUENCE DCL_SCRIPTS_NEXT_ID;

DROP DOMAIN DM_PASSWORD;

COMMIT;
